### PR TITLE
Fix email address

### PR DESCRIPTION
**Pull request by jackcviers**
Fixes the email address on 87fefe33be4ee7fb2127dffb9d0a3cebb890e022 so that this is under the CLA

### CODE REVIEW

**Comment by Kazark** [comment]
Fill me in here on how this will fix it---I think my head is not in the details.

**Comment by jackcviers** [comment]
> Fill me in here on how this will fix it---I think my head is not in the details.

I had to amend the commit with git commit --amend --author --> It used my work computer's hostname because I forgot to setup git when I first did the work. Now it's got the correct address on the commit.

**Comment by Kazark** [comment]
A merge won't fix that. Amending a commit creates a new commit. The old one will still be there. I may have to do some magic to rebase the commits and see if I can fix the metadata and force-push them.

**Comment by Kazark** [comment]
Thanks for the attempt---I will see if I can fix this with a rebase on my end.

**Pull request closed without merging**
